### ISSUE TITLE
pls update, thanks

### ISSUE THREAD

**Issue by m1ten** [undersquire/perfect-github-theme#3]
update it

**Comment by m1ten** [comment]
@undersquire

**Comment by undersquire** [comment]
I don't even use VSCode anymore 💀

**Comment by m1ten** [comment]
what do you use?

**Comment by m1ten** [comment]
also vscode is the only one I can link to using vscode.dev

**Comment by m1ten** [comment]
@undersquire can I publish it, asking for permission?

**Comment by undersquire** [comment]
> what do you use?

I use Helix. And yes you can do whatever using this theme, you can continue the project if you want.
